Fb1224
eidolonsystems/ashkal pull request #2
Opened 2018-09-19 23:12 UTC by spireken

I updated the build in the Ashkal Dropbox folder.

2018-09-19 23:21 UTC, kranar requested changes
Alright, good stuff!

2018-09-19 23:21 UTC, kranar commented on Include/Ashkal/Shapes/Ellipse.hpp
> +      //! Constructs a Ellipse with width and height of 0.
Documentation typo, should be...

```Constructs an Ellipse...```

2018-09-19 23:21 UTC, kranar commented on Include/Ashkal/Shapes/Rectangle.hpp
> +#endif
End on a new line.

2018-09-19 23:21 UTC, kranar commented on Include/Ashkal/Shapes/Rectangle.hpp
> +
Add a make_square function similar to make_circle.

2018-09-19 23:21 UTC, kranar commented on Include/Ashkal/Shapes/Shapes.hpp
> +  class Triangle;
Remove semi-colon on line 11.

2018-09-19 23:21 UTC, kranar commented on Include/Ashkal/Shapes/Triangle.hpp
> +      Point m_point1;
Store the points in an ```std::array``` rather than point1, point2, point3. Then you can return get_points() by ```const&``` instead of by value.

2018-09-19 23:21 UTC, kranar commented on Include/Ashkal/Shapes/Triangle.hpp
> +#endif
End files with a new line.

2018-09-19 23:21 UTC, kranar commented on Source/Ashkal/RenderShapeVisitor.cpp
> +      auto points = triangle.get_points();
You can change this to ```auto&```

2018-09-19 23:21 UTC, kranar commented on Source/Ashkal/RenderShapeVisitor.cpp
> +      QPoint qt_points[3];
```auto qt_points = std::array<QPoint, 3>()```;

Use a for loop:

```
    for(auto i = 0; i < 3; ++i) {
      qt_points[i] = get_qt_coordinates(m_widgets, points[i]);
    }
```

2018-09-19 23:21 UTC, kranar commented on Source/Ashkal/RenderShapeVisitor.cpp
> +      painter.drawPolygon(qt_points, 3);
```drawPolygon(qt_points.data(), 3)```

2018-09-20 14:52 UTC, spireken commented on Source/Ashkal/RenderShapeVisitor.cpp
> +      QPoint qt_points[3];
The issue I had with this was that I couldn't access the underlying C/C++-style array to pass it to drawPolygon(), which takes a regular array.

2018-09-20 14:52 UTC, spireken commented on Source/Ashkal/RenderShapeVisitor.cpp
> +      QPoint qt_points[3];
Nevermind, that's untrue.

2018-09-20 15:11 UTC, kranar approved these changes

2018-09-20 15:11 UTC, merged